# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('imagen', models.ImageField(default='lenovo.jpg', upload_to='')),
                ('video', models.FileField(default='lenovo.mp4', upload_to='')),
                ('audio', models.FileField(default='macbook.mp3', upload_to='')),
            ],
        ),
    ]
