# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('metodo_pago', models.CharField(max_length=200)),
                ('producto1', models.CharField(max_length=200)),
                ('cantidad1', models.IntegerField()),
                ('producto2', models.CharField(max_length=200)),
                ('cantidad2', models.IntegerField()),
                ('producto3', models.CharField(max_length=200)),
                ('cantidad3', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
